name: PlayerTimeLimit
version: '${version}'
main: ptl.ajneb97.PlayerTimeLimit
api-version: '1.21'
softdepend: [PlaceholderAPI]
authors: [Ajneb97, Kapitan_Floww]
website: https://www.spigotmc.org/resources/96577/
commands:
  playertimelimit:
    aliases:
      - ptm